# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c6eb900e36846a5a94b90f5ac0cd0b843ca309025be906f982ded0c5f9cb2d4ace3842e402920d7e0aa7baa81fb2ba72f12107fd8b69813335dba3aea14d677

test:
  secret_key_base: 40c6a642cf92f38253b016c82d7d35de0e110b3be3280bca7da16e0fdbd0f435b479fc3bb10359d9a1c1cb46808c64235f8f94a33913711bfcccfecf73165026

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
